### ISSUE TITLE
Getting the following issue while NPM installs SPI

### ISSUE THREAD

**Issue by rahulraghu94** [thiagorp/bbb-nrf24l01#2]
7390 verbose stack     at ChildProcess.emit (events.js:110:17)
7390 verbose stack     at maybeClose (child_process.js:1019:16)
7390 verbose stack     at Process.ChildProcess._handle.onexit (child_process.js:1091:5)
7391 verbose pkgid spi@0.1.2
7392 verbose cwd /root
7393 error Linux 3.8.13-bone79
7394 error argv "node" "/usr/bin/npm" "install" "bbb-nrf24l01"
7395 error node v0.12.13
7396 error npm  v3.8.5
7397 error code ELIFECYCLE
7398 error spi@0.1.2 install: `node-gyp rebuild`
7398 error Exit status 1
7399 error Failed at the spi@0.1.2 install script 'node-gyp rebuild'.
7399 error Make sure you have the latest version of node.js and npm installed.
7399 error If you do, this is most likely a problem with the spi package,
7399 error not with npm itself.
7399 error Tell the author that this fails on your system:
7399 error     node-gyp rebuild
7399 error You can get information on how to open an issue for this project with:
7399 error     npm bugs spi
7399 error Or if that isn't available, you can get their info via:
7399 error     npm owner ls spi
7399 error There is likely additional logging output above.
7400 verbose exit [ 1, true ]

**Comment by rahulraghu94** [comment]
It also threw this error a little above.

 ^
../src/spi_binding.cc:351:1: note: in expansion of macro 'SPI_FUNC_BOOLEAN_TOGGLE_IMPL'
 SPI_FUNC_BOOLEAN_TOGGLE_IMPL(GetSetBitOrder, SPI_LSB_FIRST);
 ^
_spi.target.mk:85: recipe for target 'Release/obj.target/_spi/src/spi_binding.o' failed
make: **\* [Release/obj.target/_spi/src/spi_binding.o] Error 1
make: Leaving directory '/root/node_modules/spi/build'
